apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.claimName }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi